platform :ios, '11'

target 'nutrition-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nutrition-app
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'TextFieldEffects'
  pod 'iOSDropDown'
  pod 'CheckBox'
  
  target 'nutrition-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nutrition-appUITests' do
    # Pods for testing
  end

end
